# -*- coding: utf-8 -*-
"""
VipTempMail client using nodriver browser automation.
viptempmail.com uses Livewire (405 for direct API), so we drive the real UI.

Usage pattern:
    mail = VipTempMailClient()
    await mail.start()
    email = await mail.get_new_email()      # opens page, reads generated email
    await mail.wait_for_code(max_wait=120)  # polls inbox, extracts 6-digit code
    await mail.close()
"""
import asyncio
import re
import random
import string
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace")


class VipTempMailClient:
    BASE = "https://viptempmail.com"

    def __init__(self):
        self.browser = None
        self.tab = None
        self.email = None

    async def _js(self, script):
        try:
            r = await self.tab.evaluate(script)
            return "" if r is None else str(r)
        except Exception:
            return ""

    async def start(self):
        import nodriver as uc
        self.browser = await uc.start(
            headless=False,
            browser_args=["--disable-gpu", "--window-size=800,700"],
        )
        return self

    async def get_new_email(self):
        """Open viptempmail.com, wait for generated email, return it."""
        self.tab = await self.browser.get(self.BASE)
        # Wait for email to appear in the page/JS
        email = None
        for i in range(30):
            await asyncio.sleep(1)
            # Email appears in the DOMContentLoaded script: const email = 'xxx@viptempmail.com'
            email = await self._js("""
                (() => {
                    // try the sidebar display element first
                    const el = document.querySelector('#email_id');
                    if (el && el.textContent.includes('@')) return el.textContent.trim();
                    // fallback: parse from page scripts
                    const m = document.documentElement.outerHTML.match(/const\\s+email\\s*=\\s*'([^']+@viptempmail\\.com)'/);
                    if (m) return m[1];
                    return '';
                })()
            """)
            if email and "@" in email:
                break
        if not email or "@" not in email:
            raise RuntimeError("no email generated by viptempmail.com")
        self.email = email
        print(f"[VIPMAIL] email: {email}")
        return email

    async def wait_for_code(self, max_wait=120):
        """Poll inbox for a 6-digit verification code."""
        print(f"[VIPMAIL] waiting for code at {self.email}...")
        for i in range(max_wait // 5):
            await asyncio.sleep(5)
            # Click Refresh button (Livewire fetchMessages)
            await self._js("""
                (() => {
                    const refresh = document.getElementById('refresh');
                    if (refresh) refresh.click();
                    if (window.Livewire) window.Livewire.emit('fetchMessages');
                })()
            """)
            await asyncio.sleep(2)
            body = await self._js("document.body.innerText") or ""
            # subject contains code like "123456 is your account verification code"
            m = re.search(r'\b(\d{6})\b', body)
            # Be careful: page may contain other numbers; require "code" context
            m2 = re.search(r'(\d{6})\s*(?:is your|verification|code)', body, re.I)
            if m2:
                code = m2.group(1)
                print(f"[VIPMAIL] found code: {code} ({(i+1)*5}s)")
                return code
            if m and ("verification" in body.lower() or "code" in body.lower()):
                code = m.group(1)
                print(f"[VIPMAIL] found code: {code} ({(i+1)*5}s)")
                return code
            if i % 4 == 0:
                print(f"[VIPMAIL] waiting... ({(i+1)*5}s)")
        return None

    async def close(self):
        try:
            if self.browser:
                self.browser.stop()
        except Exception:
            pass


async def _selftest():
    m = VipTempMailClient()
    await m.start()
    email = await m.get_new_email()
    print(f"got email: {email}")
    # keep browser open a bit to manually send a test email if desired
    await asyncio.sleep(10)
    await m.close()


if __name__ == "__main__":
    asyncio.run(_selftest())
